s339428326/AlphaCamp-Twitter

src/App.js, src/components/MainReplyModal/MainReplyModal.module.scss, src/components/MainTweetModal/MainTweetModal.module.scss
=> fix: reply modal and tweet modal input settig

src/components/AuthInput/AuthInput.jsx, src/components/AuthInput/AuthInput.module.scss, src/components/FollowButton/FollowButton.jsx, src/components/FollowButton/FollowButton.module.scss, src/components/UserProfilePart/UserProfilePart.jsx, src/pages/AdminPage.jsx, src/pages/RegisterPage.jsx, src/pages/UserLoginPage.jsx
新增共用元件FollowButton，修改AuthInput 些許樣式
=> 新增共用元件FollowButton 與 AuthInput

src/components/TopUser/TopUser.jsx, src/components/TopUser/TopUser.module.scss, src/pages/UserFollowPage.jsx, src/pages/UserMainPage.jsx, src/pages/UserMainReplyPage.jsx
=> feat: add TopUser component and apply it to other page

src/pages/UserProfilePage.jsx, src/pages/index.js
=> layout: add UserProfilePage

src/App.js, src/components/PageTitle/PageTitle.jsx, src/components/Tweet/Tweet.jsx, src/components/UserProfileTabs/UserProfileTabs.jsx, src/components/UserProfileTweet/UserProfileTweet.jsx, src/pages/UserProfilePage.jsx
PageTitle 新增 arrow button 新增上一頁的功能
Tweet 因應元件更新新增props width heigh
新增動態路由
新增outlet 使用元件  UserProfileTweet
更換UserProfileTab 使用useLocation 切換，刪除多餘useState 與switch 語法
=> 新增動態路由及因應元件更新新增props

src/components/AuthInput/AuthInput.module.scss, src/components/UserProfileTabs/UserProfileTabs.jsx
auto fill color same as input background color
=> fix:auto fill color same as input background color

src/components/UserSidebar/UserSidebar.jsx, src/components/UserSidebar/UserSidebar.module.scss, src/pages/UserSettingPage.jsx
修正UserSidebar的問題跟UserSettingPage的衝突
=> modify:UserSidebar & UserSettingPage

src/apis/.auth.js, src/contexts/AuthContext.jsx, src/pages/UserLoginPage.jsx, src/pages/UserSettingPage.jsx
=> Feature login api

src/apis/auth.js, src/contexts/AuthContext.jsx
=> docs: change auth.js naming

src/apis/userData.js, src/components/UserProfilePart/UserProfilePart.jsx, src/components/UserProfilePart/UserProfilePart.module.scss, src/pages/UserProfilePage.jsx
=> feat:read userData api

src/apis/auth.js, src/contexts/AuthContext.jsx, src/pages/AdminPage.jsx, src/pages/UserMainPage.jsx
新增 
checkpermission API 串接
adminLogin API 串接
=> feat:checkpermission, adminLogin api

src/App.js, src/components/PageTitle/PageTitle.jsx, src/components/UserProfilePart/UserProfilePart.jsx, src/components/UserProfileTabs/UserProfileTabs.jsx, src/components/UserProfileTweet/UserProfileTweet.jsx, src/components/UserSidebar/UserSidebar.jsx, src/pages/UserProfilePage.jsx
1.更新profile 加載呈現狀態
2.修正PageTitle tweet Count 文字處理
3.新增userProfileBar tweet 路由
4.修正訪問其他使用者無法透過UserSideBar 訪問自己profile的錯誤
=> Feature profile api

src/components/AdminSidebar/AdminSidebar.jsx, src/components/AdminSidebar/AdminSidebar.module.scss
修改
adminSidebar style
新增
logout功能
adminSidebar router功能
=> modify:adminSidebar

src/apis/userData.js, src/components/Tweet/Tweet.jsx, src/components/UserProfileTweet/UserProfileTweet.jsx
1.修正Tweet元件props
2.Tweet 加入useMoment
3.UserProfile page 可以讀取使用者推文清單
=> feat:UserProfile page TweetList view

src/apis/auth.js, src/contexts/AuthContext.jsx, src/pages/RegisterPage.jsx
串接
register API
新增
SweetAlert error message
=> feat:register API

src/App.js, src/apis/userData.js, src/components/UserFollowPart/UserFollowPart.jsx, src/components/UserFollowPart/UserFollowPart.module.scss, src/components/UserFollowTabs/UserFollowTabs.jsx, src/pages/UserFollowPage.jsx
render followerList and followingList
=> Feature follow api

src/components/UserProfilePart/UserProfilePart.jsx
=> fix:UserProfile page upload close button view change error

src/components/MainCreateTweet/MainCreateTweet.jsx, src/components/MainTweetModal/MainTweetModal.jsx, src/components/UserSidebar/UserSidebar.jsx, src/contexts/AuthContext.jsx, src/pages/UserFollowPage.jsx, src/pages/UserMainPage.jsx
optimize user experience when refresh the page
=> Feature main page api

src/apis/adminUsers.js, src/apis/auth.js, src/components/AdminUserCard/AdminUserCard.jsx, src/components/AdminUserCard/AdminUserCard.module.scss, src/components/AdminUserList/AdminUserList.module.scss, src/pages/AdminUserPage.jsx, src/pages/UserLoginPage.jsx
串接
adminUsers API
調整
AdminUserCard & AdminUserList 的樣式
=> feat:adminUserAPI

src/apis/userData.js, src/components/MainReply/MainReply.jsx, src/components/MainReply/MainReply.module.scss, src/components/UserLikeTweet/UserLikeTweet.jsx, src/components/UserLikeTweet/UserLikeTweet.module.scss, src/components/UserProfileTweet/UserProfileTweet.jsx
=> feat: UserProfileBar switch view

src/App.js, src/apis/userData.js, src/components/MainReply/MainReply.jsx, src/components/MainReply/MainReply.module.scss, src/components/UserLikeTweet/UserLikeTweet.jsx, src/components/UserLikeTweet/UserLikeTweet.module.scss, src/components/UserProfilePart/UserProfilePart.jsx, src/components/UserProfilePart/UserProfilePart.module.scss, src/components/UserProfileTweet/UserProfileTweet.jsx, src/pages/UserProfilePage.jsx
=> feat:add MainReply Link and  UerLilkeTweet Link

src/components/MainReplyModal/MainReplyModal.jsx, src/components/MainReplyModal/MainReplyModal.module.scss, src/components/UserLikeTweet/UserLikeTweet.jsx, src/components/UserProfilePart/UserProfilePart.jsx, src/components/UserProfileTweet/UserProfileTweet.jsx, src/pages/UserProfilePage.jsx
=> feat:add UserLikeTweet modal view

src/components/MainReplyModal/MainReplyModal.jsx, src/components/Tweet/Tweet.jsx
=> feat: v1 reply modal function

.gitignore, src/components/MainCreateTweet/MainCreateTweet.jsx, src/components/MainReplyModal/MainReplyModal.jsx, src/components/Tweet/Tweet.jsx, src/components/UserLikeTweet/UserLikeTweet.jsx, src/components/UserProfilePart/UserProfilePart.jsx, src/components/UserProfileTweet/UserProfileTweet.jsx, src/contexts/AuthContext.jsx, src/pages/UserMainPage.jsx, src/pages/UserProfilePage.jsx
更改UserSiderBar 每次點擊需要重新撈取資料的邏輯
=> fix: UserSideBar slow

src/apis/auth.js, src/apis/userData.js, src/components/Setting/Setting.jsx, src/components/TopUser/TopUser.jsx, src/components/TopUser/TopUser.module.scss, src/components/TopUserList/TopUserList.jsx, src/components/TopUserList/TopUserList.module.scss, src/contexts/TopUsersContext.jsx, src/pages/UserMainPage.jsx, src/pages/UserProfilePage.jsx, src/pages/UserSettingPage.jsx
串接
TopUser API、Setting API
切版
TopUser 樣式
=> feat:TopUser API & Setting API

src/components/TopUser/TopUser.jsx, src/pages/UserFollowPage.jsx
follow page import top user lists
=> Feature v2/button function

src/components/MainCreateTweet/MainCreateTweet.jsx, src/components/MainReplyModal/MainReplyModal.jsx, src/pages/RegisterPage.jsx
=> fix: error message for tweet susses

src/components/Setting/Setting.jsx, src/components/TopUser/TopUser.jsx, src/helpers/regex.js, src/pages/RegisterPage.jsx, src/pages/UserLoginPage.jsx
=> feat: AuthInput error message

src/components/UserSidebar/UserSidebar.jsx
=> modify: UserSidebar check currentMember

src/pages/AdminMainPage.jsx, src/pages/UserMainPage.jsx, src/pages/UserProfilePage.jsx, src/pages/UserSettingPage.jsx, src/styles/utils/_variables.scss
=> modify:userPage RWD

src/components/TopUserList/TopUserList.jsx, src/components/UserProfileTweet/UserProfileTweet.jsx, src/pages/UserMainPage.jsx, src/pages/UserMainReplyPage.jsx
=> fix: dev-tool console error

src/components/TopUserList/TopUserList.jsx
解決
當前user會出現在userList的問題
修改
只取前10名user
=> modify:TopUserList filter the same user and slice the top 10 items

README.md
Sorry, 剛剛沒有 tag 到人，我修正了一下看可不可以
=> correct: link to developers

README.md
=> fix: img renew

src/components/MainTweetModal/MainTweetModal.jsx, src/pages/UserFollowPage.jsx, src/pages/UserMainPage.jsx, src/pages/UserMainReplyPage.jsx, src/pages/UserProfilePage.jsx, src/pages/UserSettingPage.jsx
剛剛做檢查時，發現在 回覆頁面跟設定頁面時，sidebar的推文無法載入使用者大頭照，所以更改了圖檔引入方式。
=> fix: mainTweetModal avatar import method

src/components/MainReplyModal/MainReplyModal.jsx, src/components/MainReplyTweet/MainReplyTweet.jsx, src/pages/UserMainPage.jsx
=> fix: browser error

src/components/MainCreateTweet/MainCreateTweet.jsx, src/components/UserProfilePart/UserProfilePart.jsx
=> fix: new user image borken

src/components/MainReplyModal/MainReplyModal.jsx, src/components/MainTweetModal/MainTweetModal.jsx, src/components/Tweet/Tweet.jsx
fix:modal and tweet new user image broken
=> fix:modal and tweet new user image broken

src/components/AdminUserCard/AdminUserCard.jsx, src/components/AdminUserCard/AdminUserCard.module.scss, src/components/TopUserList/TopUserList.jsx, src/components/TopUserList/TopUserList.module.scss
=> modify:TopUserList userName shortened

src/components/UserLikeTweet/UserLikeTweet.jsx
fix:LikeList otherUser no view
=> fix:LikeList otherUser no view

src/components/UserSidebar/UserSidebar.jsx, src/components/UserSidebar/UserSidebar.module.scss, src/pages/AdminUserPage.jsx
=> modify: UserSidebar list item style

src/components/AuthInput/AuthInput.jsx, src/components/Setting/Setting.jsx, src/components/Tweet/Tweet.module.scss, src/components/UserSidebar/UserSidebar.module.scss, src/pages/AdminMainPage.jsx
Settin Page
1. 修改完成後，跳轉頁面至Profile
2. 用Default Value帶入currentMember資料
=> feat: Setting default value

src/apis/followship.js, src/components/FollowButton/FollowButton.jsx, src/components/MainReplyModal/MainReplyModal.jsx, src/components/MainTweetModal/MainTweetModal.jsx, src/helpers/sweetalert.js
修正 modal 字數，及 follow button waiting 狀態
=> Modify correction

src/components/FollowButton/FollowButton.jsx, src/components/MainReplyModal/MainReplyModal.jsx
=> fix: user cannot follow himself

src/components/Setting/Setting.jsx
=> fix:two logout

src/components/Setting/Setting.jsx, src/pages/UserFollowPage.jsx
=> layout:RWD follow page

src/components/MainReply/MainReply.jsx
=> fix: avatar fix

src/components/Setting/Setting.jsx
修正setting page 更新帳號名稱，未在profile page 更新的錯誤
=> fix:setting page change name bug

src/contexts/AuthContext.jsx
=> fix: first render alert fixed

src/pages/UserLoginPage.jsx
=> fix:Link naming
